# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: retobackend
custom: 
  documentation:
    version: '1'
    title: 'My API reto backend'
    description: 'This is my API para el reto backend de prueba'
    models: {} 
  default_stage: dev
  VM_DATABASE_URI: '127.0.0.1'
  VM_DATABASE_USER: 'cerebelum'  
  VM_DATABASE_PASS: 'cerebelum'
  VM_DATABASE_PORT: 3306
  VM_DATABASE_NAME: 'dbcarlos'

  # default_stage: qa
  # VM_DATABASE_URI: ''
  # VM_DATABASE_USER: 'userqa'  
  # VM_DATABASE_PASS: 'passwordqa'
  # VM_DATABASE_PORT: 3306
  # VM_DATABASE_NAME: 'bd_testqa'

  
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: "3"
plugins:
  - serverless-offline
  - serverless-openapi-documentation

provider:
  name: aws
  runtime: nodejs18.x

# you can overwrite defaults here
  stage: ${opt:stage, self:custom.default_stage}
  environment:    
    DATABASE_URI:  ${self:custom.VM_DATABASE_URI}
    DATABASE_USER: ${self:custom.VM_DATABASE_USER}
    DATABASE_PASS: ${self:custom.VM_DATABASE_PASS}
    DATABASE_PORT: ${self:custom.VM_DATABASE_PORT}
    DATABASE_NAME: ${self:custom.VM_DATABASE_NAME}
# region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iam:
#    role:
#      statements:
#        - Effect: "Allow"
#          Action:
#            - "s3:ListBucket"
#          Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#        - Effect: "Allow"
#          Action:
#            - "s3:PutObject"
#          Resource:
#            Fn::Join:
#              - ""
#              - - "arn:aws:s3:::"
#                - "Ref" : "ServerlessDeploymentBucket"
#                - "/*"

# you can define service wide environment variables here
  

# you can add packaging information here
#package:
#  patterns:
#    - '!exclude-me.js'
#    - '!exclude-me-dir/**'
#    - include-me.js
#    - include-me-dir/**

functions:
 create:
    handler: handler.create
    events:
      - http:
          path: /users
          method: post
          documentation:
            summary: Crea un usuario
            description: Crea un usuario y genera un ID unico
            requestBody:
              description: No tiene request body
 read:
    handler: handler.read
    events:
      - http:
          path: /users
          method: get
          documentation:
            summary: obtiene un listado de usuarios
            description: Obtiene el listado de todos los usuarios registrados
            requestBody:
              description: No tiene request body
 readSwapi:
    handler: handler.readSwapi
    events:
      - http:
          path: /people/{id}
          method: get
          documentation:
            summary: obtiene un jedi
            description: Obtiene informacion de un jedi por ID
            requestBody:
              description: ID numerico entero identificador del jedi
 hello:
    handler: handler.hello
#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
#    events:
#      - httpApi:
#          path: /users/create
#          method: get
#      - websocket: $connect
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
#      - alexaSkill: amzn1.ask.skill.xx-xx-xx-xx
#      - alexaSmartHome: amzn1.ask.skill.xx-xx-xx-xx
#      - iot:
#          sql: "SELECT * FROM 'some_topic'"
#      - cloudwatchEvent:
#          event:
#            source:
#              - "aws.ec2"
#            detail-type:
#              - "EC2 Instance State-change Notification"
#            detail:
#              state:
#                - pending
#      - cloudwatchLog: '/aws/lambda/hello'
#      - cognitoUserPool:
#          pool: MyUserPool
#          trigger: PreSignUp
#      - alb:
#          listenerArn: arn:aws:elasticloadbalancing:us-east-1:XXXXXX:listener/app/my-load-balancer/50dc6c495c0c9188/
#          priority: 1
#          conditions:
#            host: example.com
#            path: /hello

#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
